### ISSUE TITLE
Doesn't work for Super Mario 64 NX V8

### ISSUE THREAD

**Issue by Nolij** [exelix11/dvr-patches#29]
On latest Super Mario 64 NX V8 this has no effect. Confirmed working on Smash Ultimate on same device, just doesn't apply to SM64NX.

Title ID is `054507E0B7552000`

**Comment by exelix11** [comment]
That seems to be an homebrew, to record it you must launch it with title takeover and not the album applet.

If that doesn't work they probably don't respect some OS requirement for recording or they're using an old version of libnx. Since that's open source they can probably fix it in code by calling the relevant recording APIs rather than relying on me to patch it lol.
